# environment
task_list:
  - muti_scenario-v0
  - straight_config_traffic-v0
  - single_scenario-v0

task: straight_config_traffic-v0
modality: state

# training
training:

  use_vec_env: False  # 是否使用向量化环境
  env_num: 1  # 向量化环境中的环境数量（仅在 use_vec_env 为 True 时生效）
  show_render_info: True  # 是否显示渲染信息（仅在 use_vec_env 和save_video均为False时生效）
  lane_num: 4  # 车道数量
  algo_choose: 1  # 算法选择：1: SAC + opti

# wandb configuration
wandb:
  use_wandb: True
  wandb_project: Chapter_1
  wandb_entity: shuo_yang

# misc
misc:
  seed: 10  # 随机种子
  eval_freq: 100000  # 评估频率（每多少步评估一次）
  eval_episodes: 1  # 每次评估的 episode 数量
  save_video: False  # 是否保存视频

# environment-specific settings
env:
  env_name: metadrive-v0  # 环境名称
