# Units:
# distance [m], speed [m/s], acceleration [m/s^2]

FRENET:
  MAX_S: 4000                                                  # [int] max frenet s value available in global route
  D_MAX_S: 200
  CAR_LENGTH: 5.00                                              # the length of vehicle Tesla Model3
  CAR_WIDTH: 2.00                                               # the width of vehicle Tesla Model3

GYM_ENV:
  FIXED_REPRESENTATION: True                                    # actors's states have fixed positions in the observation tensor
  TRACK_LENGTH: 750                                             # [int] distance to travel on s axis before terminating the episode. Must be less than CARLA.MAX_S - 50
  TARGET_SPEED: 13.88                                           # Ego's target speed
  MAX_SPEED: 6.94                                              # 25km/h
  MIN_SPEED: 5.56                                              # 20km/h
  MAX_ACC: 6.878                                                # equivalent to 24.7608 km/h.s for Tesla model 3
  LOOK_BACK: 30                                                 # [int] Steps to look back at last path for observation sequence vector
  TIME_STEP: 4                                                  # [int] Steps to look back at last path for observation sequence vector (TIME_STEP + 1)
  LOOP_BREAK: 50                                                # NOT USED [int] steps to break path following while loop  - must be greater than LOOK_BACK
  DISTN_FRM_VHCL_AHD: 200                                       # Effective distance to keep from vehicle ahead for IDM
  LANE_WIDTH: 3.5

TRAFFIC_MANAGER:
  MIN_SPEED: 3.33                   # 15km/h                            # Min speed for actors in random traffic, 8.33
  MAX_SPEED: 5.00                   # 18km/h                         # Max speed for actors in random traffic  11.11