[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "head"
version = "0.1.0"
requires-python = ">=3.9,<3.12"
description = "HEAD project"
authors = [{name = "Shuo Yang", email = "shuo_yang@tongji.edu.cn"}]
dependencies = []

[tool.setuptools]
package-dir = {head = ".", evaluation = "../evaluation"}
include-package-data = false

[tool.setuptools.packages.find]
where = [".."]
include = ["head", "head.*", "evaluation", "evaluation.*"]
exclude = ["head.scenario_datasets*", "head.build*", "head.dist*",
           "head.*.build*", "head.*.__pycache__*"]
namespaces = true

[tool.setuptools.package-data]
head = [
    "configs/*.yaml",
    "agents/**/*.yaml",
    "agents/**/LICENSE*",
    "agents/**/*.md",
    "configs/tasks/*.yaml",
    "policy/evolvable_policy/common/cfgs/*.yaml"
]
