# environment
task_list:
  - muti_scenario-v0
  - straight_config_traffic-v0
  - single_scenario-v0
  - real_scenario-v0 # Poly在 real_scenario下暂无部署模式

task: real_scenario-v0
modality: state

# training
training:
  use_vec_env: False  # 是否使用向量化环境
  env_num: 1  # 向量化环境中的环境数量（仅在 use_vec_env 为 True 时生效）
  show_render_info: True  # 是否显示渲染信息（仅在 use_vec_env 和save_video均为False时生效）
  lane_num: 4  # 车道数量

# 算法具体配置
algorithm:
  mode: deployment  # 可选：evolutionary / deployment /imitation ，用于明确启用哪类算法

  # --- 进化算法配置（用于训练和进化策略） ---
  evolutionary:
    base_algorithm_type:
      main: Poly
      candidates:
        - Poly
        - Zero

    evolution_method_type:
      main: RLBoost
      sub: SAC
      candidates:
        RLBoost:
          - SAC
          - PPO
        DreamMethod:
          - HeadMethodInDream

  # ---------------- Deployment Configuration ----------------
  deployment:
    deployment_method:
      main: imitation    # 当前部署方法，可选 IDM / Poly / imitation
      candidates:
        - IDM
        - Poly
        - imitation

     # 具体配置项
    config:
      # --- IDM 部署 ---
      IDM:
        type: rule_based
        description: Intelligent Driver Model baseline

      # --- Poly 部署 ---
      Poly:
        type: learned_policy
        description: Polynomial-based policy model

      # --- Imitation Learning 部署 ---
      imitation:
        type: imitation_learning
        description: Imitation learning policy deployment
        model:
          main: wayformer
          candidates:
            - wayformer
            - MTR
            - autobot
          pretrained_path: /home/test/git_shuo/HEAD/head/policy/imitation_policy/checkpoints/brier_fde=1.45.ckpt
        dataset:
          source: /datasets/
          preprocessing: standardize



# misc
misc:
  seed: 10  # 随机种子
  eval_freq: 100000  # 评估频率（每多少步评估一次）
  eval_episodes: 30  # 每次评估的 episode 数量
  save_video: True  # 是否保存视频

# environment-specific settings
env:
  env_name: metadrive-v0  # 环境名称

# wandb configuration
wandb:
  use_wandb: False
  wandb_project: Head
  wandb_entity: shuo_yang

